refactor: support server side validation
refinedev/real-world-example pull request #3
Opened 2023-08-01 13:45 UTC by yildirayunlu

2023-08-01 15:08 UTC, alicanerdurmaz approved these changes

2023-08-01 15:09 UTC, alicanerdurmaz requested changes

2023-08-01 15:09 UTC, alicanerdurmaz commented on src/pages/auth/RegisterPage.tsx
> +                      // required: true,
```suggestion
                       required: true,
```

2023-08-04 13:48 UTC, omeraplak approved these changes

2023-08-04 14:15 UTC, alicanerdurmaz approved these changes

2023-08-09 07:21 UTC, omeraplak approved these changes

2023-08-14 06:34 UTC, merged